<option value="1"<?php if($pr["c_dob_day"]=='1'){ echo "selected";}?>>1</option>
<option value="2"<?php if($pr["c_dob_day"]=='2'){ echo "selected";}?>>2</option>
<option value="3"<?php if($pr["c_dob_day"]=='3'){ echo "selected";}?>>3</option>
<option value="4"<?php if($pr["c_dob_day"]=='4'){ echo "selected";}?>>4</option>
<option value="5"<?php if($pr["c_dob_day"]=='5'){ echo "selected";}?>>5</option>
<option value="6"<?php if($pr["c_dob_day"]=='6'){ echo "selected";}?>>6</option>
<option value="7"<?php if($pr["c_dob_day"]=='7'){ echo "selected";}?>>7</option>
<option value="8"<?php if($pr["c_dob_day"]=='8'){ echo "selected";}?>>8</option>
<option value="9"<?php if($pr["c_dob_day"]=='9'){ echo "selected";}?>>9</option>
<option value="10"<?php if($pr["c_dob_day"]=='10'){ echo "selected";}?>>10</option>
<option value="11"<?php if($pr["c_dob_day"]=='11'){ echo "selected";}?>>11</option>
<option value="12"<?php if($pr["c_dob_day"]=='12'){ echo "selected";}?>>12</option>
<option value="13"<?php if($pr["c_dob_day"]=='13'){ echo "selected";}?>>13</option>
<option value="14"<?php if($pr["c_dob_day"]=='14'){ echo "selected";}?>>14</option>
<option value="15"<?php if($pr["c_dob_day"]=='15'){ echo "selected";}?>>15</option>
<option value="16"<?php if($pr["c_dob_day"]=='16'){ echo "selected";}?>>16</option>
<option value="17"<?php if($pr["c_dob_day"]=='17'){ echo "selected";}?>>17</option>
<option value="18"<?php if($pr["c_dob_day"]=='18'){ echo "selected";}?>>18</option>
<option value="19"<?php if($pr["c_dob_day"]=='19'){ echo "selected";}?>>19</option>
<option value="20"<?php if($pr["c_dob_day"]=='20'){ echo "selected";}?>>20</option>
<option value="21"<?php if($pr["c_dob_day"]=='21'){ echo "selected";}?>>21</option>
<option value="22"<?php if($pr["c_dob_day"]=='22'){ echo "selected";}?>>22</option>
<option value="23"<?php if($pr["c_dob_day"]=='23'){ echo "selected";}?>>23</option>
<option value="24"<?php if($pr["c_dob_day"]=='24'){ echo "selected";}?>>24</option>
<option value="25"<?php if($pr["c_dob_day"]=='25'){ echo "selected";}?>>25</option>
<option value="26"<?php if($pr["c_dob_day"]=='26'){ echo "selected";}?>>26</option>
<option value="27"<?php if($pr["c_dob_day"]=='27'){ echo "selected";}?>>27</option>
<option value="28"<?php if($pr["c_dob_day"]=='28'){ echo "selected";}?>>28</option>
<option value="29"<?php if($pr["c_dob_day"]=='29'){ echo "selected";}?>>29</option>
<option value="30"<?php if($pr["c_dob_day"]=='30'){ echo "selected";}?>>30</option>
<option value="31"<?php if($pr["c_dob_day"]=='31'){ echo "selected";}?>>31</option>
